from . import foodics_tax_mapping
from . import foodics_branch
from . import foodics_payment_method
from . import foodics_pos_order_line
from . import foodics_pos_order_payment
from . import foodics_pos_order
from . import foodics_config
from . import foodics_webhook_log
from . import res_partner
from . import account_move
